_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("ctw1500_poly_train_rotate_pos",)
  TEST: ("ctw1500_poly_test",)

MODEL:
  WEIGHTS: "output/r_50_poly/pretrain/pretrain.pth"  # or the provided pre-trained model

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (24000,)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 100000 # No ckpt

INPUT:
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1280

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "output/r_50_poly/ctw1500/tune"
